<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="!$(AssemblyName.EndsWith('.Tests')) AND !$(AssemblyName.EndsWith('.Api'))">
    <Authors>phrkdll</Authors>
    <PackageProjectUrl>https://codeberg.com/phreakadelle/weavly</PackageProjectUrl>
    <RepositoryUrl>https://codeberg.com/phreakadelle/weavly</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="!$(AssemblyName.EndsWith('.Tests')) AND !$(AssemblyName.EndsWith('.Api'))">
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup Condition="!$(AssemblyName.EndsWith('.Tests'))">
    <None Include="$(SolutionDir)LICENSE.md" Pack="true" PackagePath="">
      <Visible>false</Visible>
    </None>
    <None Include="$(SolutionDir)README.md" Pack="true" PackagePath="">
      <Visible>false</Visible>
    </None>
  </ItemGroup>
  <ItemGroup Condition="!$(AssemblyName.EndsWith('.Cli')) AND !$(AssemblyName.EndsWith('.Tests')) AND !$(AssemblyName.StartsWith('Weavly.Api'))">
    <Using Include="Weavly.Core.Shared.Implementation" />
  </ItemGroup>
  <ItemGroup Condition="$(AssemblyName.EndsWith('.Tests')) OR $(AssemblyName.EndsWith('.Tests.Shared'))">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Testably.Abstractions.Testing" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="DotNetEnv" Version="3.2.0" />
    <PackageVersion Include="Fluid.Core" Version="2.31.0" />
    <PackageVersion Include="GoogleAuthenticator" Version="3.2.0" />
    <PackageVersion Include="MailKit" Version="4.17.0" />
    <PackageVersion Include="Mapster" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="MongoDB.Driver" Version="3.10.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.17" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.53.1" />
    <PackageVersion Include="Testably.Abstractions" Version="10.3.0" />
    <PackageVersion Include="Testably.Abstractions.Testing" Version="7.0.1" />
    <PackageVersion Include="WolverineFx" Version="6.24.5" />
    <PackageVersion Include="WolverineFx.RuntimeCompilation" Version="6.24.5" />
  </ItemGroup>
  <!-- Test -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
  </ItemGroup>
</Project>