name: Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: codeberg-small

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Install csharpier
        run: | 
          dotnet tool install -g csharpier
          export PATH="$PATH:$HOME/.dotnet/tools"
        
      - name: Check formatting
        run: csharpier check .

      - name: Build solution
        run: dotnet build
        
      - name: Run tests
        run: dotnet test
