name: Publish packages

on:
  push:
    tags:
      - "*.*.*"

jobs:
  packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Pack projects
        run: dotnet pack -p:PackageVersion=${{ github.ref_name }}

      - name: Publish packages
        run: dotnet nuget push "**/*.nupkg" -s https://nuget.pkg.github.com/phrkdll/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols
